/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.scribblegame;

public final class R {
    public static final class array {
        public static final int stroke=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int animation=0x7f020001;
        public static final int bottom_bar=0x7f020002;
        public static final int bottom_bar_highlight=0x7f020003;
        public static final int customize_pen_normal=0x7f020004;
        public static final int customize_pen_selected=0x7f020005;
        public static final int edit=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int pen=0x7f020008;
        public static final int scribble_image_normal=0x7f020009;
        public static final int scrollbar_horizontal_thumb=0x7f02000a;
        public static final int scrollbar_horizontal_track=0x7f02000b;
        public static final int star=0x7f02000c;
        public static final int star_orange_filled=0x7f02000d;
        public static final int star_orange_frame=0x7f02000e;
        public static final int tools=0x7f02000f;
    }
    public static final class id {
        public static final int TextView01=0x7f060001;
        public static final int bottomBar=0x7f060005;
        public static final int bottomMenu=0x7f060006;
        public static final int connection_status=0x7f06000b;
        public static final int contentViewLayout=0x7f060004;
        public static final int enter=0x7f060007;
        public static final int ipaddress=0x7f060008;
        public static final int loadimage=0x7f06000c;
        public static final int penConfig=0x7f060003;
        public static final int selectcolor=0x7f060000;
        public static final int sendButton=0x7f06000f;
        public static final int sendmessage=0x7f06000e;
        public static final int start_share=0x7f060009;
        public static final int stop_share=0x7f06000a;
        public static final int strokeWidth=0x7f060002;
        public static final int targetimage=0x7f06000d;
    }
    public static final class layout {
        public static final int customizepen=0x7f030000;
        public static final int customslidingtabhost=0x7f030001;
        public static final int getipview=0x7f030002;
        public static final int main=0x7f030003;
        public static final int scribbleimageview=0x7f030004;
        public static final int sendimage=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int strokewidth=0x7f040002;
    }
 public static final class new {
 public static final int rr=2;
}
